In [2]:
import tensorflow as tf

Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor

In [3]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_bool = tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [5]:
tensor_string = tf.constant('hellow world')
print(tensor_string)

tf.Tensor(b'hellow world', shape=(), dtype=string)


In [6]:
tensor_one_d = tf.constant([2,0,-3,8,90.1], dtype = tf.float32) #dtype specifies how much memory is to be allocated to the variable

casted_tensor_one_d = tf.cast(tensor_one_d, dtype = tf.int16) #cast  will change data type, i.e from int to float or boolean
print(tensor_one_d)

tf.Tensor([ 2.   0.  -3.   8.  90.1], shape=(5,), dtype=float32)


In [7]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [8]:
tensor_three_d = tf.constant([[[1,2,0],
 [3,5,-1]],
 [[10,2,0],
  [1,0,2]],
  [[5,8,0],
   [2,7,0]],
   [[2,1,9],
    [4,-3,32]]])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [9]:
print(tensor_three_d.ndim) #ndim tells us how many dimensions is our tensor

3


In [10]:
tensor_four_d = tf.constant(
 [
 [[[1,2,0],
 [3,5,-1]],
 [[10,2,0],
  [1,0,2]],
  [[5,8,0],
   [2,7,0]],
   [[2,1,9],
    [4,-3,32]]],

[[[13,26,0],
 [3,5,-12]],
 [[10,2,0],
  [1,0,23]],
  [[5,8,0],
   [2,7,0]],
   [[2,1,9],
    [4,-30,32]]],

[[[103,26,0],
 [3,50,-12]],
 [[100,2,0],
  [1,0,23]],
  [[5,28,0],
   [2,3,0]],
   [[22,1,9],
    [44,-320,32]]]

])
print(tensor_four_d)

tf.Tensor(
[[[[   1    2    0]
   [   3    5   -1]]

  [[  10    2    0]
   [   1    0    2]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4   -3   32]]]


 [[[  13   26    0]
   [   3    5  -12]]

  [[  10    2    0]
   [   1    0   23]]

  [[   5    8    0]
   [   2    7    0]]

  [[   2    1    9]
   [   4  -30   32]]]


 [[[ 103   26    0]
   [   3   50  -12]]

  [[ 100    2    0]
   [   1    0   23]]

  [[   5   28    0]
   [   2    3    0]]

  [[  22    1    9]
   [  44 -320   32]]]], shape=(3, 4, 2, 3), dtype=int32)


In [11]:
import numpy as np

In [12]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array) #this converts a numpy array to a tensor 

In [14]:
eye_tensor =tf.eye(
num_rows = 3,
batch_shape=[2,] #this tells us how many identiy matrix
)
print(eye_tensor) #eye tensor Returns a 2-D tensor with ones on the diagonal and zeros elsewhere

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [15]:
fill_tensor = tf.fill([2,2,3],8) #creates a tensor with a scalar value
print(fill_tensor)

tf.Tensor(
[[[8 8 8]
  [8 8 8]]

 [[8 8 8]
  [8 8 8]]], shape=(2, 2, 3), dtype=int32)


In [16]:
ones_tensor = tf.ones([5,3]) #fills with ones
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [17]:
print(tf.shape(tensor_three_d))

tf.Tensor([4 2 3], shape=(3,), dtype=int32)


In [18]:
random_tensor = tf.random.normal([3,2],mean = 10, stddev = 4) #creates a random tensor that is normally distributed values
print(random_tensor)

tf.Tensor(
[[ 8.792714    6.472342  ]
 [ 9.232388    7.8179994 ]
 [ 0.43278503 10.768731  ]], shape=(3, 2), dtype=float32)


In [19]:
random_tensor_uniform = tf.random.uniform([5,],minval=0,maxval=10)
print(random_tensor_uniform)

tf.Tensor([6.965914   9.5992985  6.350217   0.49147487 6.9599104 ], shape=(5,), dtype=float32)


In [20]:
tf.random.set_seed(5)
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))

tf.Tensor([0.45824468 4.783611   0.14864683], shape=(3,), dtype=float32)
tf.Tensor([4.922207  3.6823196 1.6838181], shape=(3,), dtype=float32)
tf.Tensor([4.9109178 3.6035519 3.8738008], shape=(3,), dtype=float32)
tf.Tensor([2.2287745 1.9468254 0.9572488], shape=(3,), dtype=float32)
tf.Tensor([1.215176   3.0175824  0.03483772], shape=(3,), dtype=float32)


In [21]:
tf.random.set_seed(5)
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))
print(tf.random.uniform([3,],minval=0,maxval=5, seed=10))

tf.Tensor([0.45824468 4.783611   0.14864683], shape=(3,), dtype=float32)
tf.Tensor([4.922207  3.6823196 1.6838181], shape=(3,), dtype=float32)
tf.Tensor([4.9109178 3.6035519 3.8738008], shape=(3,), dtype=float32)
tf.Tensor([2.2287745 1.9468254 0.9572488], shape=(3,), dtype=float32)
tf.Tensor([1.215176   3.0175824  0.03483772], shape=(3,), dtype=float32)


Indexing

In [22]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[0])
print(tensor_indexed[1:6:2]) #start from 1 index and go to 6 by skipping by 2ll

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([ 6  4 66], shape=(3,), dtype=int32)


In [23]:
print(tensor_two_d)
print(tensor_two_d[:,0:2])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 5]
 [1 5]
 [2 3]], shape=(4, 2), dtype=int32)


In [24]:
print(tensor_three_d)
print(tensor_three_d[0:3,0:2,0:2])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  5]]

 [[10  2]
  [ 1  0]]

 [[ 5  8]
  [ 2  7]]], shape=(3, 2, 2), dtype=int32)


In [25]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]]) #a+bj abs = sqrt(a^2+b^2)
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [26]:
tf.constant(3.0) / 0.0
tf.math.divide_no_nan(3.0, 0.0) #Computes a safe divide which returns 0 if y (denominator) is zero

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [27]:
#if performing math with 2 tensors that are not of equal length it broadcasts the shorter one, which is stretching it out
x1 = tf.constant([5,3,6,6,4,6])
x2 = tf.constant([7])
x2_stretched = tf.constant([7,7,7,7,7,7])
print(tf.math.add(x1,x2))
print(tf.math.add(x1,x2_stretched))

tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)
tf.Tensor([12 10 13 13 11 13], shape=(6,), dtype=int32)


In [28]:
x1 = tf.constant([5,3,6,6,4,6])
x2 = tf.constant([[7],[5],[3]])
print(tf.math.multiply(x1,x2))

tf.Tensor(
[[35 21 42 42 28 42]
 [25 15 30 30 20 30]
 [15  9 18 18 12 18]], shape=(3, 6), dtype=int32)


In [29]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]] x^y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]])>

In [30]:
print(tensor_two_d)
print(tf.math.reduce_sum(tensor_two_d)) #adds up all the elements in the tensor
print(tf.math.reduce_sum(tensor_two_d,axis=0)) #sums from the axis 0, vertical
print(tf.math.reduce_sum(tensor_two_d,axis=1)) #sums from the axis 1, horizontal


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)
tf.Tensor([ 3  7 12 13], shape=(4,), dtype=int32)


In [36]:
x = tf.constant([[2, 2, 5], [3, 3, 7],[2, 3, 12]])
y = tf.constant([[8, 16, 9], [2, 3, 10],[2, 4, 3]])
print(tf.linalg.matmul(x,y)) #matrix multiplication, rows must equal columns
print(x@y) #also multiplies

tf.Tensor(
[[30 58 53]
 [44 85 78]
 [46 89 84]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[30 58 53]
 [44 85 78]
 [46 89 84]], shape=(3, 3), dtype=int32)


In [37]:
tf.transpose(x) #makes rows become columns and columns become rows

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  2],
       [ 2,  3,  3],
       [ 5,  7, 12]])>